spring.application.name=aggregator

aggregator.kafka.bootstrap-servers=localhost:9092
aggregator.kafka.topic.sensors=telemetry.sensors.v1
aggregator.kafka.topic.snapshots=telemetry.snapshots.v1
aggregator.kafka.consumer.group-id=aggregator-group