server:
  port: 8080

grpc:
  server:
    port: 59091

spring:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: telemetry.serialization.AvroSerializer

  application:
    name: collector

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

collector:
  kafka:
    topic:
      sensors: telemetry.sensors.v1
      hubs: telemetry.hubs.v1

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
